from student_v3_121 import Student

def main():

     s1 = Student('Boris Spassky', 21345654)
     s2 = Student('Bobby Fischer', 21907321)
     s3 = Student('Mikhail Tal', 21884786)

     print(s1)
     s1.add_grade('p', 'O8')
     print(s1)
     s1.add_grade('o', 'O7')
     print(s1)
     s1.add_grade('n', 'O6')
     print(s1)
     s1.add_grade('m', 'O5')
     print(s1)
     s1.add_grade('l', 'O4')
     print(s1)
     s1.add_grade('k', 'O3')
     print(s1)
     s1.add_grade('j', 'O2')
     print(s1)
     s1.add_grade('i', 'O1')
     print(s1)
     s1.add_grade('h', 'H8')
     print(s1)
     s1.add_grade('g', 'H7')
     print(s1)
     s1.add_grade('f', 'H6')
     print(s1)
     s1.add_grade('e', 'H5')
     print(s1)
     s1.add_grade('d', 'H4')
     print(s1)
     s1.add_grade('c', 'H3')
     print(s1)
     s1.add_grade('b', 'H2')
     print(s1)
     s1.add_grade('a', 'H1')
     print(s1)

if __name__ == '__main__':
     main()
